server:
  port: 8090

spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/
    fetch-registry: false
    register-with-eureka: false


